services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    depends_on:
      - postgres
        # condition: service_healthy
    build:
      context: ../
      dockerfile: ./prod-docker/Dockerfile
    environment:
      POSTGRES_USER: ${DATABASE_URL}
    ports:
      - 3000:3000
    command: yarn start
    
